# Release 2: Reflect
# - What concepts did you review or learn in this challenge?
	# ...
# - What is still confusing to you about Ruby?
	# ...
# - What are you going to study to get more prepared for Phase 1?
	# ...